// ReSharper disable InconsistentNaming
namespace ProBonoTracker.Models
{
    public static class Enums
    {
        public enum CaseType
        {
            SIJSPredicateOrder,
            SIJSAdjustmentApplication,
            UACAsylum,
            AWCAsylum,
            AsylumOother,
            UVisa,
            VAWASelfPetition,
            VAWACancellation,
            AsyleeAdjustmentofStatus,
            Naturalization,
            DACA,
            FamilyBasedPetition,
            RemovalDefense
        }
        public enum States
        {
            AL,
            AK,
            AZ,
            AR,
            CA,
            CO,
            CT,
            DE,
            FL,
            GA,
            HI,
            ID,
            IL,
            IN,
            IA,
            KS,
            KY,
            LA,
            ME,
            MD,
            MA,
            MI,
            MN,
            MS,
            MO,
            MT,
            NE,
            NV,
            NH,
            NJ,
            NM,
            NY,
            NC,
            ND,
            OH,
            OK,
            OR,
            PA,
            RI,
            SC,
            SD,
            TN,
            TX,
            UT,
            VT,
            VA,
            WA,
            WV,
            WI,
            WY
        }
        public enum Gender
        {
            Agender,
            Female,
            Male,
            TransMale,
            TransFemale,
            GenderFluid,
            Other
        }
    }
}